# Generated by Django 3.1.7 on 2021-04-03 14:10

import api.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to='', validators=[api.validation.validate_file]),
        ),
    ]
