# Generated by Django 3.1.7 on 2021-04-29 05:27

from django.db import migrations, models
import visual.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timefile', models.FileField(upload_to='media/')),
                ('sampling_frequency', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/', validators=[visual.validators.validate_file])),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
