# Generated by Django 3.1.7 on 2021-04-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcefile',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
