# Generated by Django 3.1.7 on 2021-03-25 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0002_fileupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
